apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-nodeless-lambda
spec:
  template:
    spec:
      serviceAccountName: lambda-execute
      containers:
      - name: nodeless
        image: shirou/k8s-nodeless
        env:
          - name: FUNC
            value: "arn:aws:lambda:ap-northeast-1:9999999999999:function:test-eks-lambda-invoke"
          - name: JSON
            value: "true"
          - name: PAYLOAD
            value: "{\"time\": \"fooo\"}"
      restartPolicy: Never
  backoffLimit: 1